# project
export PROJECT_HOME=$PWD
export PROJECT_NAME=${PWD##*/}
export PROJECT_OWNER={{ direnv_project_owner }}

# aws
export AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_REGION=AWS_DEFAULT_REGION
export AWS_DEFAULT_AVAILABILITY_ZONE=AWS_DEFAULT_AVAILABILITY_ZONE
export AWS_DEFAULT_EC2_AMI={{ direnv_aws_default_ec2_ami }}

