daemonize {{ redis_daemonize }}
pidfile {{ redis_pid_file }}
port {{ redis_port }}
timeout {{ redis_timeout }}
tcp-keepalive {{ redis_tcp_keepalive }}
loglevel {{ redis_loglevel }}
logfile {{ redis_log_file }}
databases {{ redis_databases }}
{{ redis_database_save }}
stop-writes-on-bgsave-error {{ redis_stop_writes_on_bgsave_error }}
rdbcompression {{ redis_rdbcompression }}
rdbchecksum {{ redis_rdbchecksum }}
dbfilename {{ redis_db_file }}
dir {{ redis_data_dir }}
slave-serve-stale-data {{ redis_slave_serve_stale_data }}
slave-read-only {{ redis_slave_read_only }}
repl-ping-slave-period {{ redis_repl_ping_slave_period }}
repl-timeout {{ redis_repl_timeout }}
repl-disable-tcp-nodelay {{ redis_repl_disable_tcp_nodelay }}
repl-backlog-size {{ redis_repl_backlog_size }}
slave-priority {{ redis_slave_priority }}
maxclients {{ redis_maxclients }}
maxmemory-policy {{ redis_maxmemory_policy }}
maxmemory-samples {{ redis_maxmemory_samples }}
appendonly {{ redis_appendonly }}
appendfilename "{{ redis_appendfilename }}"
appendfsync {{ redis_appendfsync }}
no-appendfsync-on-rewrite {{ redis_no_appendfsync_on_rewrite }}
auto-aof-rewrite-percentage {{ redis_auto_aof_rewrite_percentage }}
auto-aof-rewrite-min-size {{ redis_auto_aof_rewrite_min_size }}
lua-time-limit {{ redis_lua_time_limit }}
slowlog-log-slower-than {{ redis_slowlog_log_slower_than }}
slowlog-max-len {{ redis_slowlog_max_len }}
notify-keyspace-events "{{ redis_notify_keyspace_events }}"
hash-max-ziplist-entries {{ redis_hash_max_ziplist_entries }}
hash-max-ziplist-value {{ redis_hash_max_ziplist_value }}
list-max-ziplist-entries {{ redis_list_max_ziplist_entries }}
list-max-ziplist-value {{ redis_list_max_ziplist_value }}
set-max-intset-entries {{ redis_set_max_intset_entries }}
zset-max-ziplist-entries {{ redis_zset_max_ziplist_entries }}
zset-max-ziplist-value {{ redis_zset_max_ziplist_value }}
activerehashing {{ redis_activerehashing }}
{{ redis_client_output_buffer_limit }}
hz {{ redis_hz }}
aof-rewrite-incremental-fsync {{ redis_aof_rewrite_incremental_fsync }}
